[package]
name = "devefi-icrc-sender"
version = "1.0.4"
description = "Sends ledger transactions"
repository = "https://github.com/Neutrinomic/devefi_icrc_sender"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
stableheapbtreemap = "1.5.0"